apiVersion: v2
kind: AtlasPipeline

pipeline:
  id: test-e2e-atlas-pipeline-with-conditions
  name: Test E2E Atlas Pipeline for python module images
  vars:
    QUBER_CLI_MODULE_IMAGE: ghcr.io/lightlessone/quber_cli:master
    MODULE_TYPE: PYTHON_DOCKER_IMAGE
    THIS_VAR_IS_A_SECRET: 42
    TEST_VAR1: 10
    TEST_VAR2: ${TEST_VAR1}000
    TEST_VAR_FOR_WHEN: clean install or something
    APP_NAMESPACES: 'ns1, ns2, zookeeper'
#  '${DEPLOY_MODE} == "Clean Install"' # '"qwerty" in TEST_VAR_FOR_WHEN.lower() and "10000" == TEST_VAR2'

  stages:
    - name: Execute Module that Has Condition1
      job: template-module-calculate
      when:
        condition: 'APP_NAMESPACES.toLowerCase().contains("zookeeper")'
      input:
        params:
          params:
            param_1: ${THIS_VAR_IS_A_SECRET}
            param_2: 2
            operation: multiply
            result_name_fake_param_to_fail_this_job: MULTIPLICATION_RESULT
      output:
        params:
          params: "*"

    - name: Execute Module that Has Condition2
      job: template-module-calculate
      when:
        statuses: SUCCESS, FAILURE
      input:
        params:
          params:
            param_1: ${TEST_VAR1}
            param_2: ${TEST_VAR2}
            operation: add
            result_name: FINAL_RESULT
      output:
        params:
          params: "*"

  jobs:
    template-module-calculate:
      path: ${QUBER_CLI_MODULE_IMAGE}
      type: ${MODULE_TYPE}
      command: calc
