apiVersion: v2
kind: AtlasPipeline

pipeline:
  id: test-e2e-atlas-pipeline
  name: Test E2E Atlas Pipeline for python module images
  vars:
    QUBER_CLI_MODULE_IMAGE: ghcr.io/lightlessone/quber_cli:master
    MODULE_TYPE: PYTHON_DOCKER_IMAGE
    THIS_VAR_IS_A_SECRET: 42
    TEST_VAR1: 10
    TEST_VAR2: ${TEST_VAR1}000

  stages:
# implicit 'prepare-common-vars' comes first if there are any vars/input params
    - name: Execute Module that Multiplies
      job: template-module-calculate
      input:
        params:
          params:
            param_1: ${THIS_VAR_IS_A_SECRET}
            param_2: 2
            operation: multiply
            result_name: MULTIPLICATION_RESULT
      output:
        params:
          params: "*"

    - name: Execute Module that Adds
      job: template-module-calculate
      input:
        params:
          params:
            param_1: ${MULTIPLICATION_RESULT}
            param_2: ${TEST_VAR2}
            operation: add
            result_name: FINAL_RESULT
      output:
        params:
          params: "*"

  jobs:
    template-module-calculate:
      path: ${QUBER_CLI_MODULE_IMAGE}
      type: ${MODULE_TYPE}
      command: calc
