name: _Execute_Image_Module

# need to change output_files (add pattern appended to files dir)
on:
  workflow_call:
    inputs:
      module_image:
        required: true
        type: string
      module_command:
        required: true
        type: string
      input_params:
        required: false
        type: string
      input_artifacts_pattern:
        required: false
        type: string
      upload_output_files:
        default: false
        required: false
        type: boolean
      output_artifact_name:
        default: output
        required: false
        type: string
    outputs:
      output_params:
        value: ${{ jobs.execute-module-command.outputs.output_params }}

# soooo, using outputs variables - is not the way, since we won't be able to use them dynamically,
# and we can't declare outputs dynamically



jobs:
  execute-module-command:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.module_image }}
    env:
      input_params: ${{ inputs.input_params }}
    outputs:
      output_params: ${{ steps.execute-module-command.outputs.output_params }}
    steps:
      - name: Prepare Module Inputs
        id: prepare-module-inputs
        run: |
          pwd
          alias module_cli="python /usr/quber/module_cli"
          module_cli generate-context-from-env --context_folder=context_folder
          cat context_folder/input/params.yaml

      - name: Download files
        id: download-files
        if: ${{ inputs.input_artifacts_pattern }}
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ inputs.input_artifacts_pattern }}
          path: context_folder/input/files
          merge-multiple: true

      - name: Execute Module
        id: execute-module-command
        run: |
          alias module_cli="python /usr/quber/module_cli"
          module_cli ${{ inputs.module_command }} --context_path=context_folder/context.yaml
          {
            echo 'output_params<<EOF'
            cat context_folder/output/params.yaml
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: Upload files
        id: upload-files
        if: ${{ inputs.upload_output_files }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.output_artifact_name }}
          path: context_folder/output/files