name: Test v3

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prepare-dynamic-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Generate GENERATED.yml
        run: |
          cat <<EOF > ./.github/workflows/GENERATED.yml
          name: GENERATED WORKFLOW
          on:
            workflow_dispatch:
          jobs:
            gen1:
              runs-on: ubuntu-latest
              steps:
                - name: Prepare
                  run: echo "Preparing"
                - name: Run
                  run: echo "Running..."
            gen2:
              needs: gen1
              runs-on: ubuntu-latest
              steps:
                - name: Finalize
                  run: echo "Finalizing..."
          EOF

      - name: Push GENERATED.yml to new branch
        run: |
          git checkout -b sub_flow_${{ github.run_number }}
          git add ./.github/workflows/GENERATED.yml
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -a -m "Create new workflow"
          git push --set-upstream origin sub_flow_${{ github.run_number }}

      - name: Run GENERATED.yml in that branch (sub_flow_${{ github.run_number }})
        run: gh workflow run 'GENERATED WORKFLOW' --ref sub_flow_${{ github.run_number }}
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}


# GENERATOR generates valid github.yml, puts it into new branch
# then we run it with 'gh workflow run' on that branch -> and provide link?
