name: Test v1

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prepare-downstream-workflow-in-caller:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: |
          echo "I'm going to create and trigger another job/workflow from this one on the fly!"
          echo "Is it even legal?"
          echo "imagine its a workflow" >> ./.github/workflows/generated.yml

  run-reusable-called-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Run downstream workflow
        run: gh workflow run ./.github/workflows/generated.yml
        env:
          GH_TOKEN: ${{ github.token }}
