apiVersion: v2
kind: AtlasPipeline

pipeline:
  id: test-e2e-atlas-pipeline-with-output
  name: Atlas Pipeline With Output
  vars:
    QUBER_CLI_MODULE_IMAGE: ghcr.io/lightlessone/quber_cli:master
    MODULE_TYPE: PYTHON_DOCKER_IMAGE
    THIS_VAR_IS_A_SECRET: ${{ secrets.REPO_SECRET_NUMBER }}
    TEST_VAR1: 9
    TEST_VAR2: ${TEST_VAR1}000

  stages:
    - name: Modules That Adds
      job: template-module-calculate
      input:
        params:
          params:
            param_1: ${TEST_VAR1}
            param_2: 10
            operation: add
            result_name: CALCULATED_PASS_RATE
      output:
        params:
          params: "*"

    - name: Modules That Downloads file
      job: template-module-calculate
      command: download-file
      input:
        params:
          params:
            url: https://raw.githubusercontent.com/Netcracker/qubership-pipelines-common-python-library/refs/heads/main/README.md
            filename: README.md
      output:
        params:
          params: '*'
        files:
          FILE_KEY3: README.md

  jobs:
    template-module-calculate:
      path: ${QUBER_CLI_MODULE_IMAGE}
      type: ${MODULE_TYPE}
      command: calc

  configuration: # pipeline configuration
    output: # output params that should be retrieved form the pipeline parameters context
      params:
        PASS_RATE: ${CALCULATED_PASS_RATE}
        params:
          PASS_RATE: ${CALCULATED_PASS_RATE}
        some_made_up_section_in_params:
          NOT_PASS_RATE: ${CALCULATED_PASS_RATE}
      params_secure:
        SOME_SECRET_TOKEN: ${THIS_VAR_IS_A_SECRET}
      files:
        FILE_KEY3: params-output.yaml
