name: _Execute_Image_Module

on:
  workflow_call:
    inputs:
      stage_id:
        required: true
        type: string
      job_id:
        required: true
        type: string
      module_image:
        required: true
        type: string
      module_command:
        required: true
        type: string
      input:
        required: false
        type: string
      output:
        required: false
        type: string

jobs:
  execute-module-command:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.module_image }}
    env:
      input: ${{ inputs.input }}
      output: ${{ inputs.output }}
      ENV_STR: ${{ inputs.env_str }}
      CI_JOB_NAME: ${{ inputs.job_id }}
      CI_JOB_STAGE: ${{ inputs.stage_id }}
    steps:
      - name: Download files
        id: download-files
        uses: actions/download-artifact@v4
        with:
          path: rt/stored_data
          merge-multiple: true

      - name: Execute Module
        id: execute-module-command
        run: |
          alias github_modules_ops="python /usr/quber/github_modules_ops"
          alias module_cli="python /usr/quber/module_cli"
          github_modules_ops prepare-data
          module_cli ${{ inputs.module_command }} --context_path rt/job_data/context.yaml
          github_modules_ops store-data
#          find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
#          cat rt/stored_data/$JOB_ID/stage.yaml
#          cat rt/job_data/context.yaml
#          cat rt/job_data/input_params.yaml

      - name: Upload files
        id: upload-files
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.job_id }}
          path: rt/stored_data